[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG_LEVEL=1
lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  knolleary/PubSubClient @ ^2.8
  adafruit/Adafruit AHTX0 @ ^2.0.5
  olikraus/U8g2 @ ^2.35.19
